### ISSUE TITLE
RangeError: Maximum call stack size exceeded when using memoryUsageWeigher with automatic expiration

### ISSUE THREAD

**Issue by harishkswamy** [aholstenson/transitory#5] opened 2018-06-19 17:09 UTC
Hi,

It looks like if I use the automatic expiration with the memoryUsageWeigher it tries to calculate the memory usage of the TimerWheel and gets into a infinite recursive loop. Is this usage expected to work?

```
const cache = transitory()
    .expireAfterRead('2s')
    .maxSize('4K')
    .withWeigher(transitory.memoryUsageWeigher)
    .build();
```

**Comment by aholstenson** [comment] 2018-06-24 08:17
Thanks for opening an issue! `transitory.memoryUsageWeigher` only works non-recursive objects, so if an object references itself in any way it will fail. So if you were putting a TimerWheel instance in the cache it wont work as the nodes in the wheel reference the wheel.

I might have misunderstood, and if so could you provide a full example, including the data you put in the cache, and the error that you are seeing?

**Comment by harishkswamy** [comment] 2018-06-24 13:58
I didn't mean to imply that I put the TimerWheel in the cache. I am saying the library is doing it if I happen to use automatic expiration with maxSize and memoryUsageWeigher. In this configuration, as provided in my previous message, transitory creates a BoudedCache Node before it weighs the memory size and it gets into an infinite loop because the Node is a circular Node. I just submitted a pull request with the fix, please take a look.

**Comment by aholstenson** [comment] 2018-06-25 06:41
Thank you! Now I understand what the problem is, sorry for the misunderstanding. I'll merge your PR and perform a release during the day.

**Comment by aholstenson** [comment] 2018-06-25 07:16
Merged and a new version has been published. Thank you for reporting the issue and creating a PR, I really appreciate it!

**Closed as completed by aholstenson** 2018-06-25 07:16 UTC

**Comment by harishkswamy** [comment] 2018-06-28 04:33
Wonderful, thanks for the quick turnaround!
